.TH SXIV 1 sxiv\-VERSION
.SH NAME
sxiv \- Simple (or small or suckless) X Image Viewer
.SH SYNOPSIS
.B sxiv
.RB [ \-bcdFfhpqrstvZ ]
.RB [ \-g
.IR GEOMETRY ]
.RB [ \-n
.IR NUM ]
.RB [ \-z
.IR ZOOM ]
.IR FILE ...
.SH DESCRIPTION
sxiv is a simple image viewer for X. It only has the most basic features
required for fast image viewing.
.P
sxiv opens all named
.IR FILE s,
or reads the names of the files to open from standard input, if only a single
hyphen\-minus
.RB ( \- )
is given.
.P
sxiv has two modes of operation: image and thumbnail mode. The default is image
mode, in which only the current image is shown. In thumbnail mode a grid of 
small previews is displayed, making it easy to choose an image to open.
.P
sxiv can also cache its thumbnails. Please see the section THUMBNAIL CACHING
for information on how to enable this feature.
.P
Please note, that the fullscreen mode requires an EWMH/NetWM compliant window
manager.
.SH OPTIONS
.TP
.B \-b
Do not show info bar on bottom of window.
.TP
.B \-c
Remove all orphaned cache files from the thumbnail cache directory and exit.
.TP
.B \-d
Scale all images to 100%, but fit large images into window.
.TP
.B \-F
Make the window fixed/floating by setting the minimum and maximum width/height
size-hints to the window width/height.
.TP
.B \-f
Start in fullscreen mode.
.TP
.BI "\-g " GEOMETRY
Set window position and size. See section GEOMETRY SPECIFICATIONS of X(7) for
more information on
.IR GEOMETRY .
.TP
.BI "\-n " NUM
Start at picture number NUM.
.TP
.B \-h
Print brief usage information to standard output and exit.
.TP
.B \-p
Pixelize images, i.e. turn off anti-aliasing.
.TP
.B \-q
Be quiet, disable warnings to standard error stream.
.TP
.B \-r
Search the given directories recursively for images to view.
.TP
.B \-s
Scale all images to fit into window.
.TP
.B \-t
Start in thumbnail mode.
.TP
.B \-v
Print version information to standard output and exit.
.TP
.B \-Z
The same as `\-z 100'.
.TP
.BI "\-z " ZOOM
Scale all images to the current zoom level, use a zoom level of
.I ZOOM
at startup.
.SH GENERAL KEYBOARD COMMANDS
The following keyboard commands are available in both image and thumbnail mode:
.TP
.B q
Quit sxiv.
.TP
.B Return
Switch to thumbnail mode / open selected image in image mode.
.TP
.BR 0 \- 9
Prefix the next command with a number (denoted via
.IR count ).
.TP
.B g
Go to the first image.
.TP
.B G
Go to the last image, or image number
.IR count .
.TP
.B f
Toggle fullscreen mode.
.TP
.B b
Toggle visibility of info bar on bottom of window.
.TP
.B A
Toggle visibility of alpha-channel, i.e. image transparency.
.TP
.B r
Reload image.
.TP
.B R
Reload all thumbnails.
.TP
.B D
Remove current image from file list and go to next image.
.SH THUMBNAIL KEYBOARD COMMANDS
The following keyboard commands are only available in thumbnail mode:
.TP
.BR h ", " Left
Move selection left
.I count
times.
.TP
.BR j ", " Down
Move selection down
.I count
times.
.TP
.BR k ", " Up
Move selection up
.I count
times.
.TP
.BR l ", " Right
Move selection right
.I count
times.
.TP
.BR Ctrl-j ", " Ctrl-Down
Scroll thumbnail grid one window height down.
.TP
.BR Ctrl-k ", " Ctrl-Up
Scroll thumbnail grid one window height up.
.SH IMAGE KEYBOARD COMMANDS
The following keyboard commands are only available in image mode:
.SS Navigate image list
.TP
.BR n ", " Space
Go
.I count
images forward.
.TP
.BR p ", " Backspace
Go
.I count
images backward.
.TP
.B [
Go
.I count
* 10 images backward.
.TP
.B ]
Go
.I count
* 10 images forward.
.SS Handle multi-frame images
.TP
.B Ctrl-n
Go to the next frame of a multi-frame image.
.TP
.B Ctrl-p
Go to the previous frame of a multi-frame image.
.TP
.B Ctrl-Space
Play/pause animation of a multi-frame image.
.SS Zooming
.TP
.BR +
Zoom in.
.TP
.B \-
Zoom out.
.TP
.B =
Set zoom level to 100%, or
.IR count %.
.TP
.B w
Set zoom level to fit image into window.
.TP
.B e
Set zoom level to fit image width to window width.
.TP
.B E
Set zoom level to fit image height to window height.
.SS Panning
.TP
.BR h ", " Left
Pan image 1/5 of window width or
.I count
pixel left.
.TP
.BR j ", " Down
Pan image 1/5 of window height or
.I count
pixel down.
.TP
.BR k ", " Up
Pan image 1/5 of window height or
.I count
pixel up.
.TP
.BR l ", " Right
Pan image 1/5 of window width or
.I count
pixel right.
.TP
.B H
Pan to left image edge.
.TP
.B J
Pan to bottom image edge.
.TP
.B K
Pan to top image edge.
.TP
.B L
Pan to right image edge.
.TP
.BR Ctrl-h ", " Ctrl-Left
Pan image one window width left.
.TP
.BR Ctrl-j ", " Ctrl-Down
Pan image one window height down.
.TP
.BR Ctrl-k ", " Ctrl-Up
Pan image one window height up.
.TP
.BR Ctrl-l ", " Ctrl-Right
Pan image one window width right.
.SS Rotation
.TP
.B <
Rotate image counter-clockwise by 90 degrees.
.TP
.B >
Rotate image clockwise by 90 degrees.
.SS Flip
.TP
.B \\\\
Flip image horizontally.
.TP
.B |
Flip image vertically.
.SS Miscellaneous
.TP
.B a
Toggle anti-aliasing.
.TP
.B W
Resize window to fit image.
.SH MOUSE COMMANDS
The following mouse mappings are available in image mode:
.SS Navigate image list
.TP
.B Button1
Go to next image.
.TP
.B Button3
Go to the previous image.
.SS Zooming
.TP
.B Ctrl+ScrollUp
Zoom in.
.TP
.B Ctrl+ScrollDown
Zoom out.
.SS Panning/Moving
.TP
.B Button2
Drag the image with the mouse while keeping this button pressed down.
.TP
.B ScrollUp
Pan image up.
.TP
.B ScrollDown
Pan image down.
.TP
.B Shift+ScrollUp
Pan image left.
.TP
.B Shift+ScrollDown
Pan image right.
.SH THUMBNAIL CACHING
To enable thumbnail caching, please make sure to create the directory
.I ~/.sxiv/
with write permissions. sxiv will then store all thumbnails inside this
directory, but it will not create this directory by itself. It rather uses the
existance of this directory as an affirmation, that the user wants thumbnails
to be cached.
.P
Use the command line option
.I \-c
to keep the cache directory clean by removing all orphaned cache files.
Additionally, run the following command afterwards inside the cache directory
to remove empty subdirectories:
.P
.RS
find \-type d \-empty \-delete
.RE
.P
If the version of
.I find
installed on your local system does not support the \-delete option, then you
can also try the following command:
.P
.RS
find . \-depth \-type d \-empty ! \-name '.' \-exec rmdir {} \\;
.RE
.SH AUTHOR
.EX
Bert Muennich   <ber.t at gmx.com>
.EE
.SH CONTRIBUTORS
.EX
Bastien Dejean  <nihilhill at gmail.com>
Dave Reisner    <d at falconindy.com>
Fung SzeTat     <sthorde at gmail.com>
.EX
.SH HOMEPAGE
.TP
https://github.com/muennich/sxiv
.SH SEE ALSO
.BR feh (1),
.BR qiv (1)
