#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) whenever an unbound key combo is used,
# with the key combo as its first argument and the path of the current image
# as its second argument.
# sxiv(1) blocks until this script terminates. It then checks if the image
# has been modified and reloads it.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

case "$1" in
"C-c")
	echo -n "$2" | xsel -i ;;
"C-e")
	urxvt -bg "#444" -fg "#eee" -sl 0 -title "$2" -e sh -c "exiv2 pr -q -pa '$2' | less" & ;;
"C-g")
	gimp "$2" & ;;
"C-comma")
	exec jpegtran -rotate 270 -copy all -outfile "$2" "$2" ;;
"C-period")
	exec jpegtran -rotate  90 -copy all -outfile "$2" "$2" ;;
"C-slash")
	exec jpegtran -rotate 180 -copy all -outfile "$2" "$2" ;;
"C-less")
	exec mogrify -rotate -90 "$2" ;;
"C-greater")
	exec mogrify -rotate +90 "$2" ;;
"C-question")
	exec mogrify -rotate 180 "$2" ;;
esac

